### PR TITLE
Policy to block bulk certconfig deletes

### PR DESCRIPTION
**Pull request by AverageMarcus**
Signed-off-by: Marcus Noble <github@marcusnoble.co.uk>

### Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Review by whites11 — APPROVED** [review]
BLOCK THIS MADNESS

**Comment by AverageMarcus** [comment]
@MarcelMue Could you please confirm that if I release a new version of this then this policy will be rolled out to MCs?

**Comment by calvix** [comment]
If I get this right if you run `kubectl delete certconfig --all` it means they the request has empty `name` value ?

**Comment by AverageMarcus** [comment]
> If I get this right if you run `kubectl delete certconfig --all` it means they the request has empty `name` value ?

Not exactly, `kubectl` actually expands that to multiple individual deletes. It's more accurate to say calling DELETE on the `/api/v1/namespaces/[namespace]/certconfig` endpoint results in an empty name value

**Comment by AverageMarcus** [comment]
Updated as it needs to be in `shared` to be pushed to all MCs

**Pull request merged**
