### PR TITLE
use pytest_helm_charts

### PR DESCRIPTION
**Pull request by ubergesundheit**
testing pr, please ignore

### CODE REVIEW

**Comment by MarcelMue** [comment]
@ubergesundheit Can we drop this PR?

**Comment by ubergesundheit** [comment]
Eventually it would be good to use `pytest_helm_charts` in this repository. It should now contain the `kubectl` functions used in this project. It would be good to have most of the projects on the `pytest_helm_charts` pytest plugin because it is tested and also released through pypi (this just fetches from a github branch)

For now it should be ok to close this PR.

**Comment by MarcelMue** [comment]
Okay - I can try to use it later on. Just not really too familiar with pipfiles :/

**Comment by MarcelMue** [comment]
Closing here - picking it up later separately.

**Pull request closed without merging**
