### PR TITLE
use pytest_helm_charts

### PR DESCRIPTION
**Pull request by ubergesundheit**
### Checklist

- [ ] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by ubergesundheit** [comment]
@MarcelMue oops just created this

**Comment by MarcelMue** [comment]
Damn nice!

**Comment by ubergesundheit** [comment]
turns out I am a dummy, `forward_requests` is not available in `pytest_helm_charts`. Ignore me while I close this PR

**Comment by MarcelMue** [comment]
_ohno_

**Pull request closed without merging**
